### ISSUE TITLE
Log function has stopped working

### ISSUE THREAD

**Issue by Pertti2012** [lainwir3d/sailfish-rpn-calculator#1]
Log function does not work, is only giving an error message "Error".
Same problem on XperiaX and JollaC, Lapuanjoki 2.1.4.14.

**Comment by AngieSoft** [comment]
syntax-error in file file common/python/rpncalc_mpmath_backend.py
line  79:
--- Backend.engineFunction("log", lambda op: mpmath.log(op, b=10), operands=1)
+++ Backend.engineFunction("log", lambda op: mpmath.log(op, 10), operands=1)

source: [(http://mpmath.org/doc/current/functions/powers.html)]

**Comment by lainwir3d** [comment]
Already fixed in commit 404fd71916c376edd9d4326cbfeabf95bb94a778
